name: env_intro_tf
dependencies:
  - python=3.6.1
  # Analysis
  - matplotlib
  - seaborn
  # Calculations
  - scikit-learn
  - nomkl
  - numpy
  # Reporting
  - pandas
  # Packages
  - pip
  - pip:
    - tensorflow
